language: objective-c
osx_image: xcode7.3

env:
  global:
    - PROJECT=KGNThread
    - SCHEME=$PROJECT
    - DESTINATION="OS=9.3,name=iPhone 6s Plus"
  # matrix:
  #   - DESTINATION="OS=8.1,name=iPhone 4s"
  #   - DESTINATION="OS=8.2,name=iPhone 5"
  #   - DESTINATION="OS=8.3,name=iPhone 5s"
  #   - DESTINATION="OS=8.4,name=iPhone 6"
  #   - DESTINATION="OS=9.0,name=iPhone 6 Plus"
  #   - DESTINATION="OS=9.1,name=iPhone 6s"
  #   - DESTINATION="OS=9.1,name=iPhone 6s Plus"
  #   - DESTINATION="OS=9.2,name=iPhone 6s"
  #   - DESTINATION="OS=9.2,name=iPhone 6s Plus"
  #   - DESTINATION="OS=9.3,name=iPhone 6s"
    # - DESTINATION="OS=9.3,name=iPhone 6s Plus"

script:
  - xcodebuild test -project "$PROJECT.xcodeproj" -scheme "$SCHEME" -sdk iphonesimulator -destination "$DESTINATION"

before_install:
  - brew update
  - brew install carthage

# before_script:
#   - carthage bootstrap

before_deploy:
  - carthage build --no-skip-current
  - carthage archive $PROJECT

deploy:
  provider: releases
  api_key:
    secure: mycjSvo4yeQGR1qi6wO6pOCbOBd2Ziva9YuW3fn4Tkd+sdUOu6sCqLRTwbfbnQCgxddlfoGgtrzmSXhyhaL0MyYTXDGxuQl5bfENVWO7qhBAXRS6IPadp9I+Selbx/LE7BvpmgZaq6dJ6MQi+YWSSk8PH/vM7JX/sVKNenRQZ4+fPB+yfCNH1oQ/lT65pQyQeP0xy6U9TLHq0m0O7eXQzM4YHYk/I0HKXjVni6qrDkjJLdJJWtquezNe7jeaI+1AReoo2LJ8/82OXAWCndIQmUDMSNwVAyA/VJNZB5EZYKgPRbJVNQUwi4KrkMpO7F4LxfTSRZR2GXDx9IsyGfo4QuqX0uTv/GnIlrt/UJ7sQr3wIOrV9FvmA8Vs9FqFGgra6fFjxFo8UntNYYrDLgcoefrL7z48Rv0BXoNYRNoJhV/QtouGr8o6zdpb3zWbIuT0Y7+CxvUVq/zcpgLoB5qxAe8CE4UnzTgzhx3ph5+vCRVE7Wq1cJDuy7kpEKYGemHPjO/7cPIv4totgpBtTFdTvIMUTJH+wM9gcoEA1O8Rowd5/HHUhhSAoT/MkOQCgQnEY3uGPVANvUzLrxYLgNhT5NtrdO3W+4a61JxUM5cnRyfg6+blacT2gZ/V0KcRkWW1JdiSt1Y5Rc2JWLCbHGvzo7mjf6ZOs8vNdSBQwv27T14=
  file: $PROJECT.framework.zip
  skip_cleanup: true
  on:
    repo: kgn/$PROJECT
    tags: true
